version: '3.0'
services:
  rasa-train:
    image: rasa/rasa:2.2.5-full
    user: root
    volumes:
      - ./:/app
    command:
      - train 
  rasa-run:
    image: rasa/rasa:2.2.5-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
      - --cors 
      - "*"
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - rasa-train
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
  action-server:
    image: rasa/rasa-sdk ##:1.10.2 nova: 2.2.0
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    command:
      - http 5005